### ISSUE TITLE
Tag "Forth"

### ISSUE THREAD

**Issue by FForth** [pzembrod/cc64#16]
Please create a "forth" tag and ... for this project. (Label "Manage topic" in open project)

**Comment by pzembrod** [comment]
Hi FForth,

I like the idea, but may I inquire who you are?

Cheers
/Philip

**Comment by FForth** [comment]
Hi
who you are?
Forth user and programmer for «fun».
I did an LCC working experiment at Forth for interest.
  
>Суббота, 13 июня 2020, 19:59 +03:00 от Philip Zembrod <notifications@github.com>:
> 
> 
>Hi FForth,
>I like the idea, but may I inquire who you are?
>Cheers
>/Philip
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
1 2

**Comment by FForth** [comment]
Hi who you are? 
Forth user and programmer for «fun». 
I did an LCC working experiment at Forth for interest.

**Comment by pzembrod** [comment]
Hi, I'm a physicist and software engineer, and am playing with Forth for fun again here, as I did 25+ years ago.
Thanks for the tag/topic tip; I added a few more topics; this sounds really useful.
LCC is nice; I have the book, and played with the compiler a bit a while ago, too.
